import { Base_URL, Request } from "./ApiHandle";

   
   const Api_Hits={
      login:(data)=>Request.post(Base_URL + "auth/login" , data),
      changePassword:(data)=>Request.patch(Base_URL + "auth/change-password" , data ),
      privacyPolicy:(data)=>Request.post(Base_URL + "privacy-policy" , data ),
      getPrivacyPolicy:()=>Request.get(Base_URL + "privacy-policy"),
      patchPrivacyPolicy:(id , data)=>Request.patch(Base_URL + `privacy-policy/${id}` , data ),
      patchUserProfile:(body)=>Request.patch(Base_URL + `auth/profile` , body ),
      getNotification:(offset , limit)=>Request.get(Base_URL + `auth/notifications?offet=${offset}&limit=${limit}`),
      readAllNotification:()=>Request.patch(Base_URL + `notification/read/all`),
      dashboardApi:(body)=>Request.get(Base_URL+`dashboard?range=${body}`),
      userProfile:()=>Request.get(Base_URL + `auth/profile`),
      users:(offset , limit)=>Request.get(Base_URL + `users?offset=${offset}&limit=${limit}`),
      userById:(id)=>Request.get(Base_URL + `users/${id}`),
      userByName:(name)=>Request.get(Base_URL + `users/search/${name}`),
      userBlock:(id)=>Request.patch(Base_URL + `users/${id}/block` ,{}),
      userUnBlock:(id)=>Request.patch(Base_URL + `users/${id}/unblock` ,{}),
      postBlock:(id)=>Request.patch(Base_URL + `posts/${id}/block` ,{}),
      postUnBlock:(id)=>Request.patch(Base_URL + `posts/${id}/unblock` ,{}),
      userPosts:(id , offset , limit)=>Request.get(Base_URL + `posts/user/${id}?offset=${offset}&limit=${limit}`),
      userPostById:(id)=>Request.get(Base_URL + `posts/${id}`),
      userPostReactions:(id)=>Request.get(Base_URL + `post/${id}/reactions`),
      userReels:(id , offset , limit)=>Request.get(Base_URL + `user/${id}/reels?offset=${offset}&limit=${limit}`),
      userReelById:(id)=>Request.get(Base_URL + `reels/${id}`),
      // userReactions:(id , offset , limit)=>Request.get(Base_URL + `/api/post/${id}/reactions` , { headers: header }),
      userFollowers:(id , offset , limit)=>Request.get(Base_URL + `user/${id}/followers?offset=${offset}&limit=${limit}`),
      userFollowing:(id , offset , limit)=>Request.get(Base_URL + `user/${id}/followings?offset=${offset}&limit=${limit}`),
      savedUsersPosts:(id, offset , limit)=>Request.get(Base_URL + `user/${id}/saved/posts?offset=${offset}&limit=${limit}`),
      savedUsersReels:(id, offset , limit)=>Request.get(Base_URL + `user/${id}/saved/reels?offset=${offset}&limit=${limit}`),
      communityPosts:( offset , limit)=>Request.get(Base_URL + `community/posts?offset=${offset}&limit=${limit}`),
      communityPostsById:(id)=>Request.get(Base_URL + `community/${id}`),
      communityPostsSearch:(userName, offset , limit, startDate, endDate)=>Request.get(Base_URL + `search?username=${userName}&startDate=${startDate ? startDate : ''}&endDate=${endDate ? endDate : ''}`),
      communityPostReactions:(id)=>Request.get(Base_URL + `community/post/${id}/reactions`),
      communityPostsComments:(id)=>Request.get(Base_URL + `community/post/${id}/comments`),
      communityPostsReplies:(id)=>Request.get(Base_URL + `comments/${id}/replies`),
      communityPostBlock:(id)=>Request.patch(Base_URL + `community/posts/${id}/block` ,{}),
      communityPostUnBlock:(id)=>Request.patch(Base_URL + `community/posts/${id}/unblock` ,{}),
      storiesBlock:(id)=>Request.patch(Base_URL + `stories/${id}/block` ,{}),
      storiesUnBlock:(id)=>Request.patch(Base_URL + `stories/${id}/unblock` ,{}),
      commentsPost:(id)=>Request.get(Base_URL + `community/post/${id}/comments`),
      commentsPostBlock:(id)=>Request.patch(Base_URL + `comments/${id}/block`),
      commentsPostUnBlock:(id)=>Request.patch(Base_URL + `comments/${id}/unblock`),
      RepliesPost:(id)=>Request.get(Base_URL + `comments/${id}/replies`),
      reportPost:(startDate,endDate, offset , limit)=>Request.get(Base_URL + `reports/posts?offset=${offset}&limit=${limit}&startDate=${startDate ? startDate : ''}&endDate=${endDate ? endDate : ''}`),
      reportReel:(startDate,endDate,offset , limit)=>Request.get(Base_URL + `reports/reels?offset=${offset}&limit=${limit}&startDate=${startDate ? startDate : ''}&endDate=${endDate ? endDate : ''}`),
      reportPostById:(id , offset , limit)=>Request.get(Base_URL + `reports/posts/${id}?offset=${offset}&limit=${limit}`),
      reportReelById:(id , offset , limit)=>Request.get(Base_URL + `reports/reels/${id}?offset=${offset}&limit=${limit}`),
      reportStories:(startDate,endDate,offset , limit)=>Request.get(Base_URL + `reports/stories?offset=${offset}&limit=${limit}&startDate=${startDate ? startDate : ''}&endDate=${endDate ? endDate : ''}`),
      reportStoriesById:(id , offset , limit)=>Request.get(Base_URL + `reports/stories/${id}?offset=${offset}&limit=${limit}`),
      reportCommunityPosts:(startDate,endDate,offset , limit)=>Request.get(Base_URL + `reports/community/posts?offset=${offset}&limit=${limit}&startDate=${startDate ? startDate : ''}&endDate=${endDate ? endDate : ''}`),
      reportCommunityPostsById:(id ,offset , limit)=>Request.get(Base_URL + `reports/community/posts/${id}?offset=${offset}&limit=${limit}`)
    
}
export default  Api_Hits;
